---

- name: Check OS string
  shell: "uname | tr '[:upper:]' '[:lower:]'"
  register: helm_os
  changed_when: no

- name: Check ARCH string
  shell: "uname -m | sed -e 's/x86_64/amd64/' -e 's/\\(arm\\)\\(64\\)\\?.*/\\1\\2/' -e 's/aarch64$/arm64/'"
  register: helm_arch
  changed_when: no

- name: Fetch helm
  get_url:
    url: "https://get.helm.sh/helm-{{ helm_version }}-{{ helm_os.stdout }}-{{ helm_arch.stdout }}.tar.gz"

    dest: /tmp/helm.tar.gz

- name: Make tempdir
  file:
    path: /tmp/helm
    state: directory

- name: Unarchive helm
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/helm
    remote_src: true

- name: Copy helm plugin to /usr/local/bin
  copy:
    src: "/tmp/helm/linux-{{ 'amd64' if ansible_architecture=='x86_64' else ansible_architecture }}/helm"
    dest: /usr/local/bin/helm
    mode: 0755
    remote_src: true
