---

- name: "Check required variables"
  assert:
    that: "{{ item.name }} is defined"
    fail_msg: "Missing variable '{{ item.name }}': {{ item.description }}"
  loop: "{{ deployment_parameters }}"

- name: "Install required pip modules"
  pip:
    name:
      - jsonpatch
      - kubernetes>=17.17.0
      - PyYAML>=5.4.1
      - hvac>=1.0.2

- name: "Get all namespaces from cluster"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ kubernetes_namespace }}"
    kubeconfig: "{{ kubernetes_kubeconfig | from_yaml }}"
  register: ns_info

- name: "Ensure namespace '{{ kubernetes_namespace }}' is available"
  kubernetes.core.k8s:
    name: "{{ kubernetes_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kubernetes_kubeconfig | from_yaml }}"
  register: create_ns
  until: not create_ns.failed
  retries: 10
  when: ns_info.resources | selectattr("metadata.name","match", kubernetes_namespace) | length != 1

- name: "Read cluster-info"
  kubernetes.core.k8s_cluster_info:
    kubeconfig: "{{ kubernetes_kubeconfig | from_yaml }}"
  register: cluster_info_output

- name: "Read incoming manifest definition"
  debug:
    msg: "{{ manifest_file | from_yaml }}"
  ignore_errors: yes

- name: "Evaluate if requested deployment is in available APIs"
  debug:
    msg: "{{ ((cluster_info_output.apis.keys() | list) + (cluster_info_output.apis.v1.keys()| list)) | select('search', (manifest_file | from_yaml).apiVersion) | length > 0 }}"
  ignore_errors: yes

- name: "Create the manifest deployment in namespace '{{ kubernetes_namespace }}'"
  kubernetes.core.k8s:
    state: present
    definition: "{{ manifest_file }}"
    kubeconfig: "{{ kubernetes_kubeconfig | from_yaml }}"
    namespace: "{{ kubernetes_namespace }}"
