---
- name: "Check required variables"
  assert:
    that: "{{ item.name }} is defined"
    fail_msg: "Missing variable '{{ item.name }}': {{ item.description }}"
  loop: "{{ deployment_parameters }}"

- name: "Install required pip modules"
  pip:
    name:
      - jsonpatch
      - kubernetes>=17.17.0
      - PyYAML>=5.4.1
      - hvac>=1.0.2

- name: "Get info about namespace '{{ kubernetes_namespace }}'"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ kubernetes_namespace }}"
    kubeconfig: "{{ kubernetes_kubeconfig | from_yaml }}"
  register: info_output

- name: "Delete deployment from namespace '{{ kubernetes_namespace }}'"
  when: info_output.resources | length != 0
  kubernetes.core.k8s:
    name: "{{ service_id }}"
    definition: "{{ manifest_file }}"
    kubeconfig: "{{ kubernetes_kubeconfig | from_yaml }}"
    namespace: "{{ kubernetes_namespace }}"
    state: absent
    wait: yes
  ignore_errors: true
