---

- name: Install required pip modules
  pip:
    name:
      - jsonpatch
      - kubernetes>12.0.0
      - PyYAML>3.11

- name: Check if Kubernetes config is available.
  stat:
    path: /etc/kubernetes/admin.conf

- name: Get Namespace
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ service_id }}"
    kubeconfig: /etc/kubernetes/admin.conf
  register: ns_info
  until: ns_info.resources | length == 0
  retries: 60

- assert:
    that: ns_info.resources | length == 0

- name: Get Service
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    namespace: "{{ service_id }}"
    kubeconfig: /etc/kubernetes/admin.conf
  register: service_info

- assert:
    that: service_info.resources | length == 0

- name: Get Deployment
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Deployment
    namespace: "{{ service_id }}"
    kubeconfig: /etc/kubernetes/admin.conf
  register: deployment_info

- assert:
    that: deployment_info.resources | length == 0

- name: Get PVC
  kubernetes.core.k8s_info:
    api_version: v1
    kind: PersistentVolumeClaim
    namespace: "{{ service_id }}"
    kubeconfig: /etc/kubernetes/admin.conf
  register: pvc_info

- assert:
    that: pvc_info.resources | length == 0