dependencies: []
galaxy_info:
  author: Lukas Rauh
  namespace: fabos.k8s
  role_name: setup
  description: Setup role for k8s
  company: Fraunhofer IPA

  license: license(MIT)

  min_ansible_version: 2.1

  platforms:
#    - name: CentOS
#      versions:
#        - 7
#        - 8
    - name: Ubuntu
      versions:
#        - 18.04
#        - 20.04
#        - 21.10
        - 22.04
#    - name: Raspbian
#      versions:
#        - 10 (Buster)

  galaxy_tags: [k8s, install, uninstall, scale up, scale down]