apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: service
  name: service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: service
    spec:
      containers:
        - env:
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "no"
            - name: MARIADB_DATABASE
              value: myuser
            - name: MARIADB_PASSWORD
              value: password123
            - name: MARIADB_ROOT_PASSWORD
              value: rootPass
            - name: MARIADB_USER
              value: myuser
          image: mariadb:10.6.4
          name: mariadb-service
          ports:
            - containerPort: 3306
          resources: {}
#          volumeMounts:
#            - mountPath: /var/lib/mysql
#              name: mariadb-data
      restartPolicy: Always
#      volumes:
#        - name: mariadb-data
#          persistentVolumeClaim:
#            claimName: mariadb-data
status: {}
