---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include CentOS Install Tasks
  ansible.builtin.include_tasks: dist-specific/centos_install.yml
  when: ansible_distribution == 'CentOS'

- name: Include Ubuntu Install Tasks
  ansible.builtin.include_tasks: dist-specific/ubuntu_install.yml
  when: ansible_distribution == 'Ubuntu'

- name: Include Raspbian Install Tasks
  ansible.builtin.include_tasks: dist-specific/raspbian_install.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_lsb.id == 'Raspbian'